[package]
name = "race-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
race-core = { path = "../core" }
race-encryptor = { path = "../encryptor" }
race-transport = { path = "../transport" }
anyhow = "1.0.64"
serde_json = "1.0.85"
serde = "1.0.144"
borsh = "0.9.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
js-sys = "0.3.60"
web-sys = { version = "0.3.60", features = ["Worker", "MessageEvent"] }
jsonrpsee = { version = "0.16.1", features = ["wasm-client"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wasmer = "3.0.2"
jsonrpsee = { version = "0.16.1", features = ["full"] }
