[package]
name = "race-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
race-core = { path = "../core" }
race-transport = { path = "../transport" }
jsonrpsee = { version = "0.16.1", features = ["full"] }
anyhow = "1.0.64"
serde_json = "1.0.85"
serde = "1.0.144"
borsh = "0.9.3"
wasmer = "3.0.2"
