[package]
name = "race-example-roshambo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
race-core = { path = "../../core" }
borsh = "0.9.3"
serde_json = "1.0.85"
serde = "1.0.144"
arrayref = "0.3.6"

[dev-dependencies]
race-test = { path = "../../test" }
