[package]
name = "race-example-minimal"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
race-core = { path = "../../core" }
race-proc-macro = { path = "../../proc-macro" }
borsh = "0.9.3"
serde_json = "1.0.85"
serde = "1.0.144"
