[workspace]
members = [
  "core",
  "proc-macro",
  "transactor",
  "cli",
  "encryptor",
  "transport",
  "facade",
  "env",
  "client",
  "client-wasm",
  "test",
  "examples/counter/core",
  "examples/minimal/core",
  "examples/console",
  "examples/holdem",
]

[profile.dev.package.num-bigint-dig]
opt-level = 3
