[workspace]

members = [
  "core",
  "transactor",
  "client",
  "facade",
  "cli",
  "solana",
  "crypto",
  "minimal",
]

exclude = [
  "holdem"
]

[profile.dev.package.num-bigint-dig]
opt-level = 3
