[workspace]
resolver = "2"
members = [
  "core",
  "proc-macro",
  "transactor",
  "cli",
  "encryptor",
  "transport",
  "facade",
  "env",
  "sdk",
  "client",
  "test",
  "examples/draw-card",
  "examples/chat",
  "examples/minimal",
  "examples/raffle",
  "examples/holdem",
]

[profile.release]
lto = true
opt-level = 3

[profile.dev.package.num-bigint-dig]
opt-level = 3

[patch.crates-io]
gloo-timers = { git = "https://github.com/rustwasm/gloo" }
