[workspace]

members = [
  "core",
  "transactor",
  "cli",
  "crypto",
  "transport",
  "facade",
  "env",
  "client",
  "examples/minimal/core"
]

[profile.dev.package.num-bigint-dig]
opt-level = 3
