[workspace]

members = [
  "core",
  "proc-macro",
  "transactor",
  "cli",
  "crypto",
  "transport",
  "facade",
  "env",
  "client",
  "examples/minimal/core",
  "examples/one-card-ranking",
  "examples/holdem",
]

[profile.dev.package.num-bigint-dig]
opt-level = 3
