[workspace]
resolver = "2"
members = [
  "core",
  "proc-macro",
  "encryptor",
  "env",
  "contracts/solana/contract",
]

[profile.release]
lto = true
opt-level = "z"

[profile.dev.package.num-bigint-dig]
opt-level = 3

[patch.crates-io]
gloo-timers = { git = "https://github.com/rustwasm/gloo" }
