holdem-simple:
    zellij --layout layouts/holdem-simple.kdl

holdem-multi:
    zellij --layout layouts/holdem-multi.kdl

demo-app:
    zellij --layout layouts/demo-app.kdl

mtt-simple:
    zellij --layout layouts/mtt-simple.kdl

ltmtt-simple:
	zellij --layout layouts/ltmtt-simple.kdl

test-sdk-sui:
    zellij --layout layouts/test-sdk-sui.kdl
