[package]
name = "race-facade"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.58"
race-core = { path = "../core" }
thiserror = "1.0.35"
serde_json = "1.0.85"
serde = "1.0.144"
futures = "0.3.24"
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }
anyhow = "1.0.64"
tokio = { version = "1.21.0", features = ["full"] }
jsonrpsee = { version = "0.16.1", features = ["full"] }
tower-http = { version = "0.3.4", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
hyper = "0.14.20"
