[package]
name = "race-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.58"
thiserror = "1.0.35"
tracing = "0.1.36"
bytes = "1.2.1"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
borsh = "0.9.3"
log = "0.4.17"
jsonrpsee = { version = "0.16.2", features = ["client-core"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.83"
