[package]
name = "race-core"
version = "0.1.0"
edition = "2021"

[dependencies]
race-proc-macro = { path = "../proc-macro" }
async-trait = "0.1.58"
thiserror = "1.0.35"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
borsh = "0.9.3"

[dev-dependencies]
anyhow = "1.0.64"
