[package]
name = "race-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, optional = true }
borsh = { workspace = true }
race-proc-macro = { path = "../proc-macro" }

[dev-dependencies]
anyhow = "1.0.64"

[features]
serde = ["dep:serde", "dep:serde_json"]
