cargo-features = ["workspace-inheritance"]

[package]
name = "race-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
borsh = { workspace = true }
