[package]
name = "race-transport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
race-core = { path = "../core" }
race-env = { path = "../env" }
async-trait = "0.1.58"
thiserror = "1.0.35"
serde_json = "1.0.85"
serde = "1.0.144"
solana-sdk = { version = "1.14.10"}
tracing = "0.1.36"

[target.'cfg(target_arch = "wasm32")'.dependencies]
jsonrpsee = { version = "0.16.2", features = ["wasm-client"]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
jsonrpsee = { version = "0.16.2", features = ["http-client"]}
