[package]
name = "race-transport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
race-core = { path = "../core" }
race-env = { path = "../env" }
jsonrpsee = { version = "0.16.1", features = ["full"] }
getrandom = { version = "0.2" }
async-trait = "0.1.58"
thiserror = "1.0.35"
serde_json = "1.0.85"
serde = "1.0.144"
solana-sdk = "1.14.10"
solana-client = "1.14.10"
web3 = "0.18.0"

[dev-dependencies]
tokio = { version = "1.21.0", features = ["full"] }
