[package]
name = "holdem"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
race-core = { path = "../../core" }
serde_json = "1.0.85"
serde = "1.0.144"
once_cell = "1.16.0"
