[transactor]
port = 12003
endpoint = "ws://localhost:12003"
chain = "facade"
address = "Server 1"
reg_addresses = ["DEFAULT_REGISTRATION_ADDRESS"]
disable_blacklist = true
debug_mode = true

[facade]
host = "http://localhost:12002"
registration_address = "DEFAULT_REGISTRATION_ADDRESS"
address = "Server 1"
