[transactor]
port = 12004
endpoint = "ws://localhost:12004"
chain = "facade"
address = "Server 2"
reg_addresses = ["DEFAULT_REGISTRATION_ADDRESS"]

[facade]
host = "http://localhost:12002"
registration_address = "DEFAULT_REGISTRATION_ADDRESS"
address = "Server 2"
