[transactor]
port = 12004
endpoint = "ws://localhost:12004"
chain = "facade"
address = "SERVER_ADDRESS_2"
reg_addresses = ["DEFAULT_REGISTRATION"]

[facade]
host = "http://localhost:12002"
registration_address = "DEFAULT_REGISTRATION"
