[package]
name = "race-env"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
shellexpand = { workspace = true }
