name: Rust Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: rustup toolchain install 1.77 --profile minimal --no-self-update

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.0

    - name: Check
      run: cargo check

    - name: Run Tests
      run: cargo test
