name: TS Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: js/package-lock.json

    - name: Install Dependencies
      run: npm i -ws --prefix ./js

    - name: Build borsh
      run: npm run build --prefix ./js/borsh

    - name: Build SDK Core
      run: npm run build --prefix ./js/sdk-core

    - name: Check
      run: npm test -ws --prefix ./js
